import {
  BarChart,
  BoxplotChart,
  CandlestickChart,
  CustomChart,
  GraphChart,
  HeatmapChart,
  LineChart,
  PictorialBarChart,
  PieChart,
  RadarChart,
  SankeyChart,
  ScatterChart,
  SunburstChart,
  TreemapChart,
} from "echarts/charts";
import {
  BrushComponent,
  CalendarComponent,
  DataZoomComponent,
  DatasetComponent,
  GraphicComponent,
  GridComponent,
  LegendComponent,
  MarkLineComponent,
  PolarComponent,
  RadarComponent,
  ToolboxComponent,
  TooltipComponent,
  VisualMapComponent,
} from "echarts/components";
import { use } from "echarts/core";
import { LabelLayout } from "echarts/features";
import { SVGRenderer } from "echarts/renderers";

export const registerEChartsModules = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  use([
    LineChart,
    BarChart,
    BoxplotChart,
    ScatterChart,
    CustomChart,
    GraphChart,
    PictorialBarChart,
    CandlestickChart,
    SunburstChart,
    PieChart,
    RadarChart,
    HeatmapChart,
    GraphicComponent,
    GridComponent,
    PolarComponent,
    LegendComponent,
    RadarComponent,
    VisualMapComponent,
    CalendarComponent,
    BarChart,
    SVGRenderer,
    MarkLineComponent,
    DataZoomComponent,
    ToolboxComponent,
    BrushComponent,
    DatasetComponent,
    SankeyChart,
    TreemapChart,
    LabelLayout,
    TooltipComponent,
  ]);
};
